name: Tests
on: 
  push:
    branches: [main]
  pull_request:
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: dom, mbstring, xml
      - name: Install dependencies
        run: composer install
        working-directory: backend
      - name: Run tests
        run: ./vendor/bin/phpunit
        working-directory: backend
